services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile_mysql
    image: gym-mysql
    container_name: intgym
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: InternationalGym
      MYSQL_USER: intgym
      MYSQL_PASSWORD: 1234
    ports:
      - "3368:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gym-net 

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: gym-php
    container_name: gymproyecto
    ports:
      - "8088:80"
      - "8443:443"
    networks:
      - gym-net
    volumes:
      - ./proyecto:/var/www/html
      - ./certs/cert.pem:/etc/ssl/certs/cert.pem
      - ./certs/privkey.pem:/etc/ssl/private/privkey.pem
      - ./apache:/etc/apache2/sites-available
    depends_on:
      - mysql
      - dns

  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: gym-dns
    ports:
      - "5355:53/udp"
      - "5355:53/tcp"
    volumes:
      - ./dns/dnsmasq.conf:/etc/dnsmasq.conf:ro
      - ./dns/hosts.local:/etc/hosts.local:ro
    networks:
      - gym-net

networks:
  gym-net:
    driver: bridge

volumes:
  mysql_data:
