services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: gym-php
    container_name: gymproyecto
    ports:
      - "8088:80"
      - "8443:443"
    volumes:
      - ./proyecto:/var/www/html
      - ./certs/cert.pem:/etc/ssl/certs/cert.pem:/etc/ssl/certs/cert.pem
      - ./certs/privkey.pem:/etc/ssl/private/privkey.pem:/etc/ssl/private/privkey.pem
    depends_on:
      - mysql
  mysql:
    build:
      context: .
      dockerfile: Dockerfile_mysql
    image: gym-mysql
    container_name: intgym
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: InternationalGym
      MYSQL_USER: intgym
      MYSQL_PASSWORD: 1234
    ports:
      - "3368:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
