SET NAMES 'utf8mb4';
SET CHARACTER SET utf8mb4;

INSERT INTO Alimentacion(objetivo, calorias, nombrePlato, descripcion, proteinas, carbohidratos, grasas, foto) VALUES ('ganar fuerza', 633, 'Sándwich de aguacate y queso', 'Verduras, proteínas y grasas saludables: en este sándwich lo tienes todo! El aguacate es rico en grasas, pero no hay de qué preocuparse: nuestro cuerpo usa esos ácidos grasos insaturados en los procesos metabolicos.', 33, 27, 41, 'sandwich.jpg');
INSERT INTO Alimentacion(objetivo, calorias, nombrePlato, descripcion, proteinas, carbohidratos, grasas, foto) VALUES ('ganar fuerza', 578, 'Tortitas con 5 ingredientes', 'Nuestras tortitas de 5 ingredientes son un desayuno delicioso y libre de gluten. ¡La mezcla se hace en un momento y solo necesitas 5 ingredientes para prepararla! (4 huevos, Queso crema (125g), Almendras molidas (60g), Canela (2g), Mantequilla (10g)', 29, 6, 48, 'tortitas.jpg');
INSERT INTO Alimentacion(objetivo, calorias, nombrePlato, descripcion, proteinas, carbohidratos, grasas, foto) VALUES ('ganar fuerza', 872, 'Pasta con espinacas y salsa de cacahuete', '¡Esta combinación de espinacas y crema de cacahuete hacen que la salsa sea deliciosa! Las espinacas congeladas te permiten preparar esta receta en menos tiempo del que necesitarías con espinacas frescas. Las espinacas tienen mucho magnesio, que ayuda a regular la presión sanguínea', 27, 73, 50, 'pasta_espinacas.jpg');
INSERT INTO Alimentacion(objetivo, calorias, nombrePlato, descripcion, proteinas, carbohidratos, grasas, foto) VALUES ('ganar fuerza', 600, 'Pechuga de pollo con arroz integral y aguacate', 'Pechuga de pollo a la planca jugosa, acompañada de arroz integral que aporta energía sostenida ay aguacate que suma grasas saludables para mejorar el aporte calórico', 45, 60, 20, 'pollo_arroz_aguacate.jpg');
INSERT INTO Alimentacion(objetivo, calorias, nombrePlato, descripcion, proteinas, carbohidratos, grasas, foto) VALUES ('ganar fuerza', 650, 'Salmón al horno con patata y verduras', 'Salmón horneado rico en omega-3, servido con patata asada para reponer energía y verduras como brócoli que aportan fibra y micronutrientes', 40, 50, 25, 'salmon_patata_verdura.jpg');
INSERT INTO Alimentacion(objetivo, calorias, nombrePlato, descripcion, proteinas, carbohidratos, grasas, foto) VALUES ('estabilidad', 350, 'Yogur con avena y frutos rojos', 'Yogur combinando con avena y frutos rojos, ujna mezcla equilibrada que aporta proteína, carbohidratos de absorción lenta y antioxidantes.', 20, 45, 10, 'yogur-avena-y-frutos-rojos.jpg');
INSERT INTO Alimentacion(objetivo, calorias, nombrePlato, descripcion, proteinas, carbohidratos, grasas, foto) VALUES ('estabilidad', 500, 'Ensalada de pollo con quinoa', 'Ensalada completa con pollo a la plancha, quinoa y verduras frescas, aliñada con aceite de oliva para un buen equilibrio nutricional', 35, 40, 15, 'ensalada_quinoa.jpg');
INSERT INTO Alimentacion(objetivo, calorias, nombrePlato, descripcion, proteinas, carbohidratos, grasas, foto) VALUES ('estabilidad', 550, 'Ternera con arroz y verduras', 'Carne magra de ternera cocinada a la plancha, acompañada de arroz y verduras salteadas que aportan energía y vitaminas.', 35, 50, 15, 'ternera.jpeg');
INSERT INTO Alimentacion(objetivo, calorias, nombrePlato, descripcion, proteinas, carbohidratos, grasas, foto) VALUES ('estabilidad', 400, 'Tortilla de huevo con espinacas', 'Tortilla ligera de huevos con espinacas, acompañada de una pequeña porción de pan integral para completar la cena', 25, 30, 15, 'tortilla_espinacas.jpeg');
INSERT INTO Alimentacion(objetivo, calorias, nombrePlato, descripcion, proteinas, carbohidratos, grasas, foto) VALUES ('estabilidad', 350, 'Merluza con verduras', 'Merluza a la plancha con verduras variadas, una opción ligera pero nutritiva ideal para la noche.', 30, 20, 10, 'merluza_verdrua.jpg');
INSERT INTO Alimentacion(objetivo, calorias, nombrePlato, descripcion, proteinas, carbohidratos, grasas, foto) VALUES ('perder peso', 250, 'Tortilla de claras con avena', 'Claras de huevo ricas en proteína combinadas con una pequeña cantidad de avena para aportar energía sin exceso calórico.', 30, 25, 5, 'tortilla_avena.jpg');
INSERT INTO Alimentacion(objetivo, calorias, nombrePlato, descripcion, proteinas, carbohidratos, grasas, foto) VALUES ('perder peso', 300, 'Ensalada de atún', 'Ensalada fresca con atún, verduras y un toque de aceite de oliva, pensada para ser saciante y baja en calorías.', 30, 15, 10, 'ensalada_atun.jpeg');
INSERT INTO Alimentacion(objetivo, calorias, nombrePlato, descripcion, proteinas, carbohidratos, grasas, foto) VALUES ('perder peso', 320, 'Pollo con verduras al vapor', 'Pechuga de pollo cocinada de forma ligera con verduras al vapor, mantendiendo bajo el contenido calórico y alto el aporte proteico.', 35, 20, 8, 'pollo_vapor.jpeg');
INSERT INTO Alimentacion(objetivo, calorias, nombrePlato, descripcion, proteinas, carbohidratos, grasas, foto) VALUES ('perder peso', 280, 'Bacalao con ensalada', 'Bacalao a la planca acompañado de ensalada verde, una cena ligera que ayuda a mantener el déficit calórico.', 30, 10, 8, 'bacalao_ensalada.jpg');
INSERT INTO Alimentacion(objetivo, calorias, nombrePlato, descripcion, proteinas, carbohidratos, grasas, foto) VALUES ('perder peso', 220, 'Revuelto de claras con verduras', 'Revuelto de claras con verduras como espinacas o champiñones, fácil de digerir y bajo en calorías.', 28, 10, 5, 'revuelto_claras.jpeg');

INSERT INTO Ejercicios(nombreEjercicio, descripcion, calorias, foto) VALUES ('Press de banca', 'Ejercicio básico donde mpujas una barra desde el pecho mientras estás tumbado, trabajando principalmente el pecho y tambíen triceps.', 5, 'press banca.jpeg');
INSERT INTO Ejercicios(nombreEjercicio, descripcion, calorias, foto) VALUES ('Flexiones', 'Movimiento con el propio peso corporal, bajando y subiendo el torso mateniendo el cuerpo recto. Muy completo  accesible.', 3, 'flexiones.jpeg');
INSERT INTO Ejercicios(nombreEjercicio, descripcion, calorias, foto) VALUES ('Dominadas', 'Levantas tu cuerpo agarrado a una barra, trabajando la esplada alta y brazos. Exigente pero muy efectivo.', 8, 'dominada.jpg');
INSERT INTO Ejercicios(nombreEjercicio, descripcion, calorias, foto) VALUES ('Remo con barra', 'Inclinado hacia delante,, tiras de una barra hacia el abdomen, activando toda la espalda media.', 5, 'remo con brra.jpg');
INSERT INTO Ejercicios(nombreEjercicio, descripcion, calorias, foto) VALUES ('Sentadillas', 'Flexión de piernas mateniendo la esplada recta, uno de los ejercicios más completos para tren inferior.', 10, 'sentadilla.jpeg');
INSERT INTO Ejercicios(nombreEjercicio, descripcion, calorias, foto) VALUES ('Prensa de piernas', 'Empijas una plataforma con los pies, trabajando cuádriceps y glúteos de forma controlada.', 8, 'prensa-pierna-2.jpg');
INSERT INTO Ejercicios(nombreEjercicio, descripcion, calorias, foto) VALUES ('Press militar', 'Empuje de barra o mancuernas por encima de la cabeza centrado en hombros y estabilidad.', 3, 'press militar.jpeg');
INSERT INTO Ejercicios(nombreEjercicio, descripcion, calorias, foto) VALUES ('Elevaciones laterales', 'Levantas mancuernas hacia los lados para aislar el hombro, especialmente la parte media.', 3, 'elevaciones.jpeg');
INSERT INTO Ejercicios(nombreEjercicio, descripcion, calorias, foto) VALUES ('Fondos en paralelas', 'Bajas y subes el cuerpo usando barras paralelalas, enfocando el trabajo en tríceps.', 5, 'fondos.jpg');
INSERT INTO Ejercicios(nombreEjercicio, descripcion, calorias, foto) VALUES ('Extensiones de tríceps', 'Extensión de brazos con peso (mancuerna o polea) para aislar el tríceps', 3, 'extensiones.jpeg');
INSERT INTO Ejercicios(nombreEjercicio, descripcion, calorias, foto) VALUES ('Curl con barra', 'Flexión de brazos levantando una barra, centrado en el bíceps.', 3, 'curl con barrra.jpg');
INSERT INTO Ejercicios(nombreEjercicio, descripcion, calorias, foto) VALUES ('Curl alterno con mancuernas', 'Variante donde trbajas cada brazo por separado, mejorando equilibrio y control.', 3, 'curl alterno.jpeg');

